USE SAKILA;
#### -------------NOTES-----------
  ## 1) SELECT * SHOWS ALL THE COLOMNS IN THE TABLE
  SELECT * FROM FILM;
  ### TO GET SPECIFIC COLOMNS IN THE TABLE
  SELECT FILM_ID,TITLE,RENTAL_DURATION,RATING FROM FILM;
  
  ###2) DISTINCT ## TO REMOVE THE DUPLICATES IN THE COLOUMN ..
     SELECT RENTAL_DURATION FROM FILM;  ## SHOWS  ALL THE DATA IN  RENTAL_DURATION COLOUMN.
     SELECT DISTINCT RENTAL_DURATION FROM FILM; ### REMOVES DUPLICATES AND SHOW UNIQUE VALUES
     
### 3) WHERE --- TO FILTER THE ROWS
  SELECT * FROM FILM;  ## GIVE ALL THE DATE OR VALUES  THE TABLE
  SELECT * FROM FILM
  WHERE RENTAL_DURATION > 5;  ## GIVES ONLY THE VALUES WHERE THE RENTAL_DURATION IS GREATER THAN (>) 5.
  
### 4) ORDER ---- TO SORT THE RESULTS.. LIKE TO GET THE RESULTS IN ORDER WISE LIKE ..ACCENDING (ASC)/DESCENDING ORDER(DESC).
 SELECT FILM_ID,TITLE, RENTAL_DURATION,RENTAL_RATE FROM FILM
 WHERE RENTAL_RATE > 0.99; ### GIVES ONLY THE REQUIRED COLOMNS WITH THE RENTAL_RATE IS GREATER THAN (>) 0.99
 SELECT FILM_ID,TITLE,RENTAL_DURATION,RENTAL_RATE FROM FILM
 WHERE RENTAL_RATE > 0.99
 ORDER BY RENTAL_RATE DESC; ### GIVES ONLY THE REQUIRED COLOMNS WITH THE RENTAL_RATE IS GREATER THAN (>) 0.99 IN DESC ORDER.
 
### 5) LIMIT ---- TO GET LIMITED VALUES OR ROWS OR DATA.alter
 SELECT FILM_ID,TITLE,RENTAL_DURATION,RENTAL_RATE FROM FILM
 WHERE RENTAL_RATE > 0.99
 ORDER BY RENTAL_RATE DESC;   ### ### (IT GAVE 659 ROWS)GIVES ONLY THE REQUIRED COLOMNS WITH THE RENTAL_RATE IS GREATER THAN (>) 0.99 IN DESC ORDER.
 SELECT FILM_ID,TITLE,RENTAL_DURATION,RENTAL_RATE FROM FILM
 WHERE RENTAL_RATE > 0.99
 ORDER BY RENTAL_RATE DESC
 LIMIT 10;     ### IT GIVE ONLY 10 ROWS LIKE FILMS WITH  TOP 10 RENTAL_RATE
 
 ###6.NULL
 select * from sakila.film
where original_language_id is null;

## 7 AND / OR
select * from sakila.film
where rental_duration =7 and ( rating = 'g' or rating ='pg')
order by rental_rate desc;
 
select * from sakila.film
where rating = 'r' and rental_duration = 5;
     
     ### 8 WILDS CARDS USING LIKE '$_%'
     SELECT * FROM SAKILA.CUSTOMER
WHERE not LAST_NAME LIKE 'SMITH' AND FIRST_NAME LIKE '%A';
  SELECT * FROM FILM
WHERE TITLE LIKE '%ACTION%' OR DESCRIPTION LIKE '%WAR%';

### 9. BETWEEN 
SELECT rental_id, inventory_id, customer_id, return_date
FROM sakila.rental
WHERE  return_date between '2005-05-26' and '2005-05-30';

## 10 COUNT()
SELECT COUNT(*) AS total_films
FROM film;

## 11 AVG()
SELECT AVG(rental_rate) AS avg_rate
FROM film;

##12  MIN(rental_rate), MAX(rental_rate)
SELECT MIN(rental_rate), MAX(rental_rate)
FROM film;

##13 SUM()
SELECT SUM(amount) AS total_payments
FROM payment;

##14 GROUP BY
SELECT customer_id,
       COUNT(*) AS total_rentals
FROM rental
GROUP BY customer_id;

##15  GROUP BY  /HAVING
SELECT customer_id,
       COUNT(*) AS total_payals
FROM payment
GROUP BY customer_id
HAVING COUNT(*) > 5;


